"""ensure_user_status_field

Revision ID: 1ee6e4c1784e
Revises: c19e031d09e3
Create Date: 2025-11-22 19:49:29.723333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee6e4c1784e'
down_revision = 'c19e031d09e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
