"""fix_subtask_is_completed_type

Revision ID: 5a093d49ae83
Revises: 3cd565591f21
Create Date: 2025-11-16 22:10:12.150558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a093d49ae83'
down_revision = '3cd565591f21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, convert enum values to boolean
    op.execute("ALTER TABLE subtasks ALTER COLUMN is_completed TYPE BOOLEAN USING (is_completed::text = 'todo')::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtasks', 'is_completed',
               existing_type=sa.Boolean(),
               type_=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', 'OVERDUE', name='taskstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
